export const AUTH_LOGGED_IN = "[AUTH] AUTH_LOGGED_IN";
export const AUTH_LOGGED_OUT = "[AUTH] AUTH_LOGGED_OUT";
export const AUTH_LOGGED_IN_ERROR = "[AUTH] AUTH_LOGGED_IN_ERROR";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_SERVICES = "GET_ALL_SERVICES";
export const GET_DASHBOARD_COUNTS = "GET_DASHBOARD_COUNTS";
